//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationSelectedTimetable
    {
        public int Id { get; set; }
        public System.Guid CommitId { get; set; }
        public int ExamBaseTimetableId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    }
}
