//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamInEntryBlock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamInEntryBlock()
        {
            this.ExamInEntryBlockUnit = new HashSet<ExamInEntryBlockUnit>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid EntryId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentExamInEntryBlockId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamInEntryBlockUnit> ExamInEntryBlockUnit { get; set; }
    }
}
