//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamInEntryBlockUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamInEntryBlockUnit()
        {
            this.ExamTimetable = new HashSet<ExamTimetable>();
            this.ApplicationSelectedExam = new HashSet<ApplicationSelectedExam>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ExamInEntryBlockId { get; set; }
        public int ExamId { get; set; }
        public Nullable<double> EgeMin { get; set; }
    
        public virtual ExamInEntryBlock ExamInEntryBlock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamTimetable> ExamTimetable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationSelectedExam> ApplicationSelectedExam { get; set; }
    }
}
