//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class extApplicationDetails
    {
        public System.Guid Id { get; set; }
        public System.Guid ApplicationId { get; set; }
        public string ObrazProgramName { get; set; }
        public string ProfileName { get; set; }
        public Nullable<int> CurrVersion { get; set; }
        public Nullable<System.DateTime> CurrDate { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public System.Guid InnerEntryInEntryId { get; set; }
        public int InnerEntryInEntryPriority { get; set; }
    }
}
