//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class extPerson
    {
        public System.Guid Id { get; set; }
        public int Barcode { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public bool Sex { get; set; }
        public Nullable<int> PassportTypeId { get; set; }
        public string PassportType { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public string PassportAuthor { get; set; }
        public Nullable<System.DateTime> PassportDate { get; set; }
        public string PassportCode { get; set; }
        public string Phone { get; set; }
        public string Mobiles { get; set; }
        public string Email { get; set; }
        public int ForeignCountryId { get; set; }
        public string Country { get; set; }
        public Nullable<int> CountryId { get; set; }
        public int RegionId { get; set; }
        public string Region { get; set; }
        public Nullable<int> ForeignNationalityId { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string Nationality { get; set; }
        public string Code { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Korpus { get; set; }
        public string Flat { get; set; }
        public string CodeReal { get; set; }
        public string CityReal { get; set; }
        public string StreetReal { get; set; }
        public string HouseReal { get; set; }
        public string KorpusReal { get; set; }
        public string FlatReal { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string Language { get; set; }
        public string Parents { get; set; }
        public string AddInfo { get; set; }
        public Nullable<bool> AbitHostel { get; set; }
        public int RegistrationStage { get; set; }
        public Nullable<bool> HasPrivileges { get; set; }
        public Nullable<bool> StartEnglish { get; set; }
        public Nullable<double> EnglishMark { get; set; }
        public bool IsImported { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<bool> HostelEduc { get; set; }
        public string KladrCode { get; set; }
        public string SNILS { get; set; }
        public int AbiturientTypeId { get; set; }
        public Nullable<bool> HasTRKI { get; set; }
        public string TRKICertificateNumber { get; set; }
        public Nullable<int> ReturnDocumentTypeId { get; set; }
        public string AddEmail { get; set; }
    }
}
