//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class FZ_152_AgreeLog
    {
        public int OrdId { get; set; }
        public System.Guid PersonId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Request_Agent { get; set; }
        public string Request_IP { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public System.DateTime BirthDate { get; set; }
    }
}
