//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxMessage
    {
        public System.Guid Id { get; set; }
        public System.Guid DialogId { get; set; }
        public System.Guid UserId { get; set; }
        public string Text { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool IsRead { get; set; }
    }
}
