//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxMessage
    {
        public System.Guid Id { get; set; }
        public System.Guid DialogId { get; set; }
        public System.Guid UserId { get; set; }
        public string Text { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool IsRead { get; set; }
    }
}
