//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxDialogUsers
    {
        public int OrdId { get; set; }
        public Nullable<System.Guid> DialogId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    }
}
