//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympBook
    {
        public System.Guid Id { get; set; }
        public int OlympLevelId { get; set; }
        public int OlympNameId { get; set; }
        public int OlympSubjectId { get; set; }
        public int OlympTypeId { get; set; }
        public int OlympYear { get; set; }
        public Nullable<int> OlympProfileId { get; set; }
    
        public virtual OlympLevel OlympLevel { get; set; }
        public virtual OlympName OlympName { get; set; }
        public virtual OlympSubject OlympSubject { get; set; }
        public virtual OlympType OlympType { get; set; }
    }
}
