//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioFilesMark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PortfolioFilesMark()
        {
            this.StatusId = 7;
        }
    
        public System.Guid PersonId { get; set; }
        public bool IsComplete { get; set; }
        public Nullable<double> RuPortfolioPts { get; set; }
        public Nullable<double> DePortfolioPts { get; set; }
        public Nullable<double> RuInterviewPts { get; set; }
        public Nullable<double> DeInterviewPts { get; set; }
        public Nullable<bool> Interview { get; set; }
        public int StatusId { get; set; }
    
        public virtual PortfolioStatus PortfolioStatus { get; set; }
    }
}
