//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolExitClassToStudyLevel
    {
        public int MaximumOrderNumberSchoolTypeId { get; set; }
        public Nullable<int> MaximumExitClassId { get; set; }
        public Nullable<int> MaximumQualificationId { get; set; }
        public int MinimumOrderNumberSchoolTypeId { get; set; }
        public Nullable<int> MinimumExitClassId { get; set; }
        public Nullable<int> MinimumQualificationId { get; set; }
        public int StudyLeveId { get; set; }
        public Nullable<int> MaxBlocks { get; set; }
        public bool IsForeign { get; set; }
    }
}
