//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolExitClassToStudyLevel
    {
        public int MaximumOrderNumberSchoolTypeId { get; set; }
        public Nullable<int> MaximumExitClassId { get; set; }
        public Nullable<int> MaximumQualificationId { get; set; }
        public int MinimumOrderNumberSchoolTypeId { get; set; }
        public Nullable<int> MinimumExitClassId { get; set; }
        public Nullable<int> MinimumQualificationId { get; set; }
        public int StudyLeveId { get; set; }
        public Nullable<int> MaxBlocks { get; set; }
        public bool IsForeign { get; set; }
    }
}
