//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013.EMDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_StudyPlanHelp
    {
        public int OrdID { get; set; }
        public int LicenseProgramId { get; set; }
        public int ObrazProgramId { get; set; }
        public int SemesterId { get; set; }
        public int CampaignYear { get; set; }
        public string StudyPlanNumber { get; set; }
        public int StudyFormId { get; set; }
    }
}
