//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddSharedFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddSharedFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AddSharedFiles", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверено.
        /// </summary>
        internal static string ApprovalStatus_Approved {
            get {
                return ResourceManager.GetString("ApprovalStatus_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cтатус.
        /// </summary>
        internal static string ApprovalStatus_Header {
            get {
                return ResourceManager.GetString("ApprovalStatus_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не проверялось.
        /// </summary>
        internal static string ApprovalStatus_NotSet {
            get {
                return ResourceManager.GetString("ApprovalStatus_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отбраковано.
        /// </summary>
        internal static string ApprovalStatus_Rejected {
            get {
                return ResourceManager.GetString("ApprovalStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер прикрепляемого файла слишком велик (максимум 4Mb).
        /// </summary>
        internal static string BigFileMessage {
            get {
                return ResourceManager.GetString("BigFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опись поданных документов.
        /// </summary>
        internal static string FileList {
            get {
                return ResourceManager.GetString("FileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя файла.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип файла.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие файлы.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить файл.
        /// </summary>
        internal static string HeaderLoadFile {
            get {
                return ResourceManager.GetString("HeaderLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это папка общих файлов. &lt;br /&gt;
        ///    Сюда вы можете прикрепить те документы, которые необходимы для всех заявлений, например, сканы паспорта, документы об образовании, переводы документов и т.п.&lt;br /&gt; &lt;b&gt;Внимание! &lt;/b&gt; Данный функционал используется только для подающих документы в магистратуру в электронно-цифровой форме! &lt;br /&gt;
        ///&lt;b&gt;Обращаем Ваше внимание! &lt;/b&gt;&lt;br /&gt;
        ///Прикрепляемым файлам необходимо давать названия, состоящие ТОЛЬКО ИЗ ЛАТИНСКИХ БУКВ и цифр, отражающие содержание документа, например: «passpo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это папка общих файлов. &lt;br /&gt;
        ///    Сюда вы можете прикрепить те документы, которые необходимы для всех заявлений, например, сканы паспорта, документы об образовании, переводы документов и т.п.&lt;br /&gt;.
        /// </summary>
        internal static string HelpMessage_AG {
            get {
                return ResourceManager.GetString("HelpMessage_AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это папка общих файлов. &lt;br /&gt;
        ///    Сюда вы можете прикрепить те документы, которые необходимы для всех заявлений: &lt;br /&gt; 1. Документ, удостоверяющий личность.&lt;br /&gt; 2. Документ об образовании.&lt;br /&gt; 3. Фотографии. &lt;br /&gt; 4. Список опубликованных научных работ.&lt;br /&gt; 5. Удостоверение о сдаче кандидатских экзаменов.&lt;br /&gt; 6. Удостоверение об окончании клинической ординатуры или интернатуры&lt;br /&gt; 7. Прочие документы&lt;br /&gt;
        ///&lt;b&gt;Обращаем Ваше внимание! &lt;/b&gt;&lt;br /&gt;
        ///Прикрепляемым файлам необходимо давать названия, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpMessage_Aspirant {
            get {
                return ResourceManager.GetString("HelpMessage_Aspirant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это папка общих файлов. &lt;br /&gt;
        ///    Сюда вы можете прикрепить те документы, которые необходимы для всех заявлений, например, сканы паспорта, документы об образовании, переводы документов и т.п.&lt;br /&gt;.
        /// </summary>
        internal static string HelpMessage_Foreign {
            get {
                return ResourceManager.GetString("HelpMessage_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не отображать отказы от конкурса и другие файлы, защищенные от удаления.
        /// </summary>
        internal static string HideSomeFiles {
            get {
                return ResourceManager.GetString("HideSomeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата загрузки.
        /// </summary>
        internal static string LoadDate {
            get {
                return ResourceManager.GetString("LoadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загруженные файлы:.
        /// </summary>
        internal static string LoadedFiles {
            get {
                return ResourceManager.GetString("LoadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет файлов.
        /// </summary>
        internal static string NoFiles {
            get {
                return ResourceManager.GetString("NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузите копию документа, удостоверяющего личность, гражданство и место регистрации поступающего.
        /// </summary>
        internal static string PassportLoad {
            get {
                return ResourceManager.GetString("PassportLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сюда вы можете прикрепить сканы паспорта. &lt;/br&gt;
        ///Остальные документы можно прикрепить в окне Общие документы. &lt;/br&gt;.
        /// </summary>
        internal static string PersonalOffice_Passport {
            get {
                return ResourceManager.GetString("PersonalOffice_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Информация для поступающих:&lt;/h3&gt;
        ///В соответствии с пунктом 2.21 Правил приема в Санкт-Петербургский государственный университет на основные образовательные программы высшего профессионального образования (программы бакалавриата, программы подготовки специалиста, программы магистратуру) в 2014 году (далее – Правила приема) для участия в конкурсе на основные образовательные программы магистратуры Вам необходимо представить следующие документы:
        ///    &lt;ul&gt;
        ///        &lt;li&gt; копию документа, удостоверяющего лично [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RulesInformation {
            get {
                return ResourceManager.GetString("RulesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
