//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddSharedFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddSharedFiles() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AddSharedFiles", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Проверено.
        /// </summary>
        internal static string ApprovalStatus_Approved {
            get {
                return ResourceManager.GetString("ApprovalStatus_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Cтатус.
        /// </summary>
        internal static string ApprovalStatus_Header {
            get {
                return ResourceManager.GetString("ApprovalStatus_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Не проверялось.
        /// </summary>
        internal static string ApprovalStatus_NotSet {
            get {
                return ResourceManager.GetString("ApprovalStatus_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Отбраковано.
        /// </summary>
        internal static string ApprovalStatus_Rejected {
            get {
                return ResourceManager.GetString("ApprovalStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Размер прикрепляемого файла слишком велик (максимум 4Mb).
        /// </summary>
        internal static string BigFileMessage {
            get {
                return ResourceManager.GetString("BigFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Комментарий.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Сюда вы можете прикрепить сканы языковых сертификатов&lt;/br&gt;
        ///Остальные документы можно прикрепить в окне Общие документы. &lt;/br&gt;.
        /// </summary>
        internal static string EnglishCertificatesLoad {
            get {
                return ResourceManager.GetString("EnglishCertificatesLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Файл.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Опись поданных документов.
        /// </summary>
        internal static string FileList {
            get {
                return ResourceManager.GetString("FileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Имя файла.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Тип файла.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Настоятельно рекомендуем загружать каждый документ цельным файлом в формате &lt;b&gt;PDF&lt;/b&gt;. &lt;br/&gt;Для загрузки фотографии можно использовать файлы JPG (JPEG, PNG)..
        /// </summary>
        internal static string FileTypeRecommend {
            get {
                return ResourceManager.GetString("FileTypeRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Общие файлы.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Загрузить файл.
        /// </summary>
        internal static string HeaderLoadFile {
            get {
                return ResourceManager.GetString("HeaderLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Это папка общих файлов. &lt;br /&gt;
        ///    Сюда вы можете прикрепить те документы, которые необходимы для всех заявлений, например, сканы паспорта, документы об образовании, переводы документов и т.п.&lt;br /&gt;.
        /// </summary>
        internal static string HelpMessage_Foreign {
            get {
                return ResourceManager.GetString("HelpMessage_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Не отображать отказы от конкурса и другие файлы, защищенные от удаления.
        /// </summary>
        internal static string HideSomeFiles {
            get {
                return ResourceManager.GetString("HideSomeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Дата загрузки.
        /// </summary>
        internal static string LoadDate {
            get {
                return ResourceManager.GetString("LoadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Загруженные файлы:.
        /// </summary>
        internal static string LoadedFiles {
            get {
                return ResourceManager.GetString("LoadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Нет файлов.
        /// </summary>
        internal static string NoFiles {
            get {
                return ResourceManager.GetString("NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Загрузите копию документа, удостоверяющего личность, гражданство и место регистрации поступающего.
        /// </summary>
        internal static string PassportLoad {
            get {
                return ResourceManager.GetString("PassportLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как PersonalOffice_Certificates.
        /// </summary>
        internal static string PersonalOffice_Certificates {
            get {
                return ResourceManager.GetString("PersonalOffice_Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Сюда вы можете прикрепить сканы паспорта. &lt;/br&gt;
        ///Остальные документы можно прикрепить в окне Общие документы. &lt;/br&gt;.
        /// </summary>
        internal static string PersonalOffice_Passport {
            get {
                return ResourceManager.GetString("PersonalOffice_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как &lt;h3&gt;Информация для поступающих:&lt;/h3&gt;
        ///В соответствии с пунктом 2.23 Правил приема в Санкт-Петербургский государственный университет на основные образовательные программы высшего профессионального образования (программы бакалавриата, программы подготовки специалиста, программы магистратуру) в 2016 году (далее – Правила приема) для участия в конкурсе на основные образовательные программы магистратуры Вам необходимо представить следующие документы:
        ///    &lt;ul&gt;
        ///        &lt;li&gt; копию документа, удостоверяющего лично [остаток строки был усечен]&quot;;.
        /// </summary>
        internal static string RulesInformation {
            get {
                return ResourceManager.GetString("RulesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Размер.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Отправить.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Просмотр.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
