//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ApplicationInfo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр условий поступления.
        /// </summary>
        internal static string AppDetails {
            get {
                return ResourceManager.GetString("AppDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не все экзамены по выбору указаны.
        /// </summary>
        internal static string AppHasNotSelectedExams {
            get {
                return ResourceManager.GetString("AppHasNotSelectedExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для одного или нескольких заявлений не указаны приоритеты образовательных программ или профилей.
        /// </summary>
        internal static string AppHasNotSpecifiedExams {
            get {
                return ResourceManager.GetString("AppHasNotSpecifiedExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для данного конкурса Вы должны указать приоритетность образовательных программ и профилей.
        /// </summary>
        internal static string AppInnerProirity {
            get {
                return ResourceManager.GetString("AppInnerProirity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для данного конкурса Вам необходимо указать приоритетность образовательных программ и профилей.
        /// </summary>
        internal static string AppInnerProirityProfile {
            get {
                return ResourceManager.GetString("AppInnerProirityProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последние изменения были внесены:.
        /// </summary>
        internal static string AppLastChanges {
            get {
                return ResourceManager.GetString("AppLastChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы отозвали это заявление. Файл с заявлением об отказе был приложен в раздел &quot;Общие документы&quot;..
        /// </summary>
        internal static string ApplicationCanceled {
            get {
                return ResourceManager.GetString("ApplicationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать заявление.
        /// </summary>
        internal static string ApplicationChange {
            get {
                return ResourceManager.GetString("ApplicationChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить заявление целиком.
        /// </summary>
        internal static string ApplicationDelete {
            get {
                return ResourceManager.GetString("ApplicationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать экзамены по выбору.
        /// </summary>
        internal static string ApplicationExamenChange {
            get {
                return ResourceManager.GetString("ApplicationExamenChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на сдачу экзамена.
        /// </summary>
        internal static string ApplicationExamenRegistration {
            get {
                return ResourceManager.GetString("ApplicationExamenRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные сведения.
        /// </summary>
        internal static string ApplicationInfoHeader {
            get {
                return ResourceManager.GetString("ApplicationInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распечатайте заявление. &lt;b&gt;Подписанное&lt;/b&gt; и отсканированное заявление загрузите в окне ниже..
        /// </summary>
        internal static string ApplicationMessage1 {
            get {
                return ResourceManager.GetString("ApplicationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распечатайте заявление. &lt;b&gt;Подписанное&lt;/b&gt; заявление отнесите в приемную комиссию, чтобы изменения вступили в силу.
        /// </summary>
        internal static string ApplicationMessage2 {
            get {
                return ResourceManager.GetString("ApplicationMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить приоритеты.
        /// </summary>
        internal static string ApplicationPriorityChange {
            get {
                return ResourceManager.GetString("ApplicationPriorityChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус заявления.
        /// </summary>
        internal static string ApplicationStatusTitle {
            get {
                return ResourceManager.GetString("ApplicationStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет информации о версии заявления. Настоятельно рекомендуем зайти в раздел &lt;b&gt;&quot;Приоритеты&quot;&lt;/b&gt; и сохранить выбранную последовательность приоритетов путем нажатия кнопки &lt;b&gt;&quot;Сохранить&quot;&lt;/b&gt;..
        /// </summary>
        internal static string AppNoLastChanges {
            get {
                return ResourceManager.GetString("AppNoLastChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус заявления:.
        /// </summary>
        internal static string AppStatus {
            get {
                return ResourceManager.GetString("AppStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отозвать заявление.
        /// </summary>
        internal static string btnCancelApplication {
            get {
                return ResourceManager.GetString("btnCancelApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения.
        /// </summary>
        internal static string btnSaveChanges {
            get {
                return ResourceManager.GetString("btnSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть письмо.
        /// </summary>
        internal static string btnViewMotivationalMail {
            get {
                return ResourceManager.GetString("btnViewMotivationalMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h5&gt;Внимание!&lt;/h5&gt;
        ///    &lt;p&gt;Отзывая данное заявление, вы отказываетесь от участия в конкурсе на указанную образовательную программу.Восстановить данное заявление будет уже невозможно.&lt;/p&gt;
        ///    &lt;h4&gt;Вы хотите отказаться от участия в конкурсе?&lt;/h4&gt;.
        /// </summary>
        internal static string CancelAppMessage {
            get {
                return ResourceManager.GetString("CancelAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание!.
        /// </summary>
        internal static string DeleteApp_Warning1 {
            get {
                return ResourceManager.GetString("DeleteApp_Warning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы собираетесь удалить данное заявление. Данное действие нельзя будет отменить. После удаления этого заявления, заявление об отказе от участия в конкурсе будет сформировано и сохранено в папку &quot;Общие документы&quot;. .
        /// </summary>
        internal static string DeleteApp_Warning2 {
            get {
                return ResourceManager.GetString("DeleteApp_Warning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить заявление?.
        /// </summary>
        internal static string DeleteApp_Warning3 {
            get {
                return ResourceManager.GetString("DeleteApp_Warning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание!&lt;/br&gt; Вы не можете удалить заявление, поскольку в нем существует конкурс, прием на который уже закрыт. Для вас доступна функция редактирования заявления и изменения приоритетов. .
        /// </summary>
        internal static string DeleteApp_Warning4 {
            get {
                return ResourceManager.GetString("DeleteApp_Warning4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать заявление.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string ExamsName {
            get {
                return ResourceManager.GetString("ExamsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние.
        /// </summary>
        internal static string ExamsStage {
            get {
                return ResourceManager.GetString("ExamsStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, прикрепляйте общие для каждого заявления файлы (сканы паспорта / документа об образовании и т.п.) в раздел.
        /// </summary>
        internal static string FilesWarning1 {
            get {
                return ResourceManager.GetString("FilesWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данный раздел прикрепляйте подписанный бланк заявления.
        /// </summary>
        internal static string FilesWarning2 {
            get {
                return ResourceManager.GetString("FilesWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить файл.
        /// </summary>
        internal static string HeaderAddFile {
            get {
                return ResourceManager.GetString("HeaderAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основная информация.
        /// </summary>
        internal static string HeaderBaseInfo {
            get {
                return ResourceManager.GetString("HeaderBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string HeaderDelete {
            get {
                return ResourceManager.GetString("HeaderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эссе.
        /// </summary>
        internal static string HeaderEssay {
            get {
                return ResourceManager.GetString("HeaderEssay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экзамены.
        /// </summary>
        internal static string HeaderExams {
            get {
                return ResourceManager.GetString("HeaderExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        internal static string HeaderFileComments {
            get {
                return ResourceManager.GetString("HeaderFileComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя файла.
        /// </summary>
        internal static string HeaderFilename {
            get {
                return ResourceManager.GetString("HeaderFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер.
        /// </summary>
        internal static string HeaderFilesize {
            get {
                return ResourceManager.GetString("HeaderFilesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мотивационное письмо.
        /// </summary>
        internal static string HeaderMotivationalMail {
            get {
                return ResourceManager.GetString("HeaderMotivationalMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В портфолио нет файлов.
        /// </summary>
        internal static string HeaderNoFiles {
            get {
                return ResourceManager.GetString("HeaderNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Портфолио.
        /// </summary>
        internal static string HeaderPortfolio {
            get {
                return ResourceManager.GetString("HeaderPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приоритетность обр.программ и профилей.
        /// </summary>
        internal static string InnerPriorities {
            get {
                return ResourceManager.GetString("InnerPriorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допущено к участию в конкурсе.
        /// </summary>
        internal static string IsAddedToProtocol {
            get {
                return ResourceManager.GetString("IsAddedToProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление одобрено.
        /// </summary>
        internal static string IsApprowed {
            get {
                return ResourceManager.GetString("IsApprowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поступило в работу.
        /// </summary>
        internal static string IsImported {
            get {
                return ResourceManager.GetString("IsImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главное меню.
        /// </summary>
        internal static string LinkMainMenu {
            get {
                return ResourceManager.GetString("LinkMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/span&gt;&lt;b&gt;В мотивационном письме должны содержаться:&lt;/b&gt; 
        ///    &lt;ul&gt;
        ///        &lt;li&gt;необходимые сведения об опыте профессиональной подготовки/деятельности;&lt;/li&gt;
        ///        &lt;li&gt;сведения, подтверждающие необходимость получения знаний/навыков, освоение/приобретение которых возможно в период обучения на выбранной программе;&lt;/li&gt;
        ///        &lt;li&gt;перспективы/планы реализации полученных знаний/навыков в будущей профессиональной деятельности.&lt;/li&gt; 
        ///&lt;li&gt; Файл не должен содержать информацию, способствующую установлению авто [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MotivationalMailInformation {
            get {
                return ResourceManager.GetString("MotivationalMailInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мотивационное письмо.
        /// </summary>
        internal static string MotiveLetter {
            get {
                return ResourceManager.GetString("MotiveLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробно для иностранных граждан (на русском ).
        /// </summary>
        internal static string MotiveLetterDetails {
            get {
                return ResourceManager.GetString("MotiveLetterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перечень программ и вступительные испытания (на русском ).
        /// </summary>
        internal static string MotiveLetterDetails2 {
            get {
                return ResourceManager.GetString("MotiveLetterDetails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href =&apos;http://abiturient.spbu.ru/index.php/russkij/informatsiya-dlya-inostrannykh-grazhdan/protsedura-podachi-dokumentov/kriterii-otsenivaniya-dokumentov&apos;&gt;.
        /// </summary>
        internal static string MotiveLetter_Link {
            get {
                return ResourceManager.GetString("MotiveLetter_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href =&apos;http://abiturient.spbu.ru/index.php/priem/magistratura/perechen-programm-i-vstupitelnye-ispytaniya-2&apos;&gt;.
        /// </summary>
        internal static string MotiveLetter_Link2 {
            get {
                return ResourceManager.GetString("MotiveLetter_Link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образовательная программа.
        /// </summary>
        internal static string ObrazProgram {
            get {
                return ResourceManager.GetString("ObrazProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центр социологических и Интернет-исследований Санкт-Петербургского университета проводит онлайн опрос абитуриентов, подавших документы в наш университет в 2016 году, и их родителей. Просим Вас принять участие в опросе.&lt;br/&gt;
        ///&lt;a href = &apos;https://opros.spbu.ru/Account/RegisterWithTicket?TicketGuid=98194da8-3f39-4a1b-b72b-8d91b8824925&apos; target=&quot;_blank&quot;&gt;&lt;b&gt;Анкета абитуриента СПбГУ&lt;/b&gt;&lt;/a&gt; &lt;br/&gt;
        ///&lt;a href = &apos;https://opros.spbu.ru/Account/RegisterWithTicket?TicketGuid=892f130c-4240-4c98-a44d-ff7dfc5e463f&apos; target=&quot;_b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Opros {
            get {
                return ResourceManager.GetString("Opros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы собираетесь закончить формирование заявления и распечатать его.&lt;/br&gt;&lt;/br&gt;Обращаем Ваше внимание!&lt;/br&gt;&lt;/br&gt;После окончательного формирования Заявления внести изменения в список программ и изменить их приоритетность можно будет только путем  удаления данного заявления и формирования нового. Внести изменения в приоритетность профилей можно будет только путем личного обращения в Комиссию по приему документов.&lt;/br&gt;&lt;/br&gt;Вы желаете закончить формирование заявления и распечатать его?.
        /// </summary>
        internal static string PrintApplicationWarning {
            get {
                return ResourceManager.GetString("PrintApplicationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам следует.
        /// </summary>
        internal static string PrintFormWarning1 {
            get {
                return ResourceManager.GetString("PrintFormWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to распечатать заявление&lt;/a&gt; и прийти с ним в приёмную комиссию.
        /// </summary>
        internal static string PrintFormWarning2 {
            get {
                return ResourceManager.GetString("PrintFormWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;abbr title=&quot;Наивысший приоритет равен 1&quot;&gt;Приоритет&lt;/abbr&gt;.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление.
        /// </summary>
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подано.
        /// </summary>
        internal static string StatusActive {
            get {
                return ResourceManager.GetString("StatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отозвано.
        /// </summary>
        internal static string StatusCancelled {
            get {
                return ResourceManager.GetString("StatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма обучения.
        /// </summary>
        internal static string StudyForm {
            get {
                return ResourceManager.GetString("StudyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о заявлении.
        /// </summary>
        internal static string Subheader {
            get {
                return ResourceManager.GetString("Subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр заявления.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр/Добавить файлы.
        /// </summary>
        internal static string ViewAddFiles {
            get {
                return ResourceManager.GetString("ViewAddFiles", resourceCulture);
            }
        }
    }
}
