//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приёмная комиссия.
        /// </summary>
        internal static string AbiturientSpbuName {
            get {
                return ResourceManager.GetString("AbiturientSpbuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Академическая гимназия.
        /// </summary>
        internal static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        internal static string DatetimePicker {
            get {
                return ResourceManager.GetString("DatetimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string ErrorPageHeader {
            get {
                return ResourceManager.GetString("ErrorPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время запроса произошла ошибка. Приносим свои извинения за доставленные неудобства..
        /// </summary>
        internal static string ErrorPageMessage {
            get {
                return ResourceManager.GetString("ErrorPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to для иностранных граждан.
        /// </summary>
        internal static string ForeignAbiturient_PageHeaderAppendix {
            get {
                return ResourceManager.GetString("ForeignAbiturient_PageHeaderAppendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет для иностранных граждан.
        /// </summary>
        internal static string ForeignAbiturient_Title {
            get {
                return ResourceManager.GetString("ForeignAbiturient_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .
        /// </summary>
        internal static string HeaderTelephoneAddress {
            get {
                return ResourceManager.GetString("HeaderTelephoneAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 (812) 328-32-91.
        /// </summary>
        internal static string HeaderTelephoneAddress_Foreign {
            get {
                return ResourceManager.GetString("HeaderTelephoneAddress_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Version.
        /// </summary>
        internal static string LanguageSelector {
            get {
                return ResourceManager.GetString("LanguageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная регистрация на поселение.
        /// </summary>
        internal static string MainNavDorms {
            get {
                return ResourceManager.GetString("MainNavDorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход для зарегистрированных.
        /// </summary>
        internal static string MainNavLogon {
            get {
                return ResourceManager.GetString("MainNavLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string MainNavRegister {
            get {
                return ResourceManager.GetString("MainNavRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образовательная программа.
        /// </summary>
        internal static string ObrazProgram {
            get {
                return ResourceManager.GetString("ObrazProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет поступающего.
        /// </summary>
        internal static string PersonalOfficeHeaderName {
            get {
                return ResourceManager.GetString("PersonalOfficeHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет поступающего в аспирантуру.
        /// </summary>
        internal static string PersonalOfficeHeaderName_Aspirant {
            get {
                return ResourceManager.GetString("PersonalOfficeHeaderName_Aspirant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет поступающего для иностранных граждан.
        /// </summary>
        internal static string PersonalOfficeHeaderName_Foreign {
            get {
                return ResourceManager.GetString("PersonalOfficeHeaderName_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет поступающего в колледж.
        /// </summary>
        internal static string PersonalOfficeHeaderName_SPO {
            get {
                return ResourceManager.GetString("PersonalOfficeHeaderName_SPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление.
        /// </summary>
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт СПбГУ.
        /// </summary>
        internal static string SiteSpbu_Name {
            get {
                return ResourceManager.GetString("SiteSpbu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Университетская наб. д. 9.
        /// </summary>
        internal static string SpbuHeaderAddress {
            get {
                return ResourceManager.GetString("SpbuHeaderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Волховский пер, д.3.
        /// </summary>
        internal static string SpbuHeaderAddress_Foreign {
            get {
                return ResourceManager.GetString("SpbuHeaderAddress_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Санкт-Петербургский Государственный Университет.
        /// </summary>
        internal static string Spbu_Title {
            get {
                return ResourceManager.GetString("Spbu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор формата поступления.
        /// </summary>
        internal static string StartPageNav {
            get {
                return ResourceManager.GetString("StartPageNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основа обучения.
        /// </summary>
        internal static string StudyBasis {
            get {
                return ResourceManager.GetString("StudyBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Госбюджетная.
        /// </summary>
        internal static string StudyBasisBudget {
            get {
                return ResourceManager.GetString("StudyBasisBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма обучения.
        /// </summary>
        internal static string StudyForm {
            get {
                return ResourceManager.GetString("StudyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очная.
        /// </summary>
        internal static string StudyFormFullTime {
            get {
                return ResourceManager.GetString("StudyFormFullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        internal static string txtShow {
            get {
                return ResourceManager.GetString("txtShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр заявления.
        /// </summary>
        internal static string txtShowHeader {
            get {
                return ResourceManager.GetString("txtShowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string UILangSetCookie {
            get {
                return ResourceManager.GetString("UILangSetCookie", resourceCulture);
            }
        }
    }
}
