//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Приёмная комиссия.
        /// </summary>
        internal static string AbiturientSpbuName {
            get {
                return ResourceManager.GetString("AbiturientSpbuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Академическая гимназия.
        /// </summary>
        internal static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как для иностранных граждан.
        /// </summary>
        internal static string ForeignAbiturient_PageHeaderAppendix {
            get {
                return ResourceManager.GetString("ForeignAbiturient_PageHeaderAppendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Личный кабинет для иностранных граждан.
        /// </summary>
        internal static string ForeignAbiturient_Title {
            get {
                return ResourceManager.GetString("ForeignAbiturient_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как   .
        /// </summary>
        internal static string HeaderTelephoneAddress {
            get {
                return ResourceManager.GetString("HeaderTelephoneAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 8 (812) 328-32-91.
        /// </summary>
        internal static string HeaderTelephoneAddress_Foreign {
            get {
                return ResourceManager.GetString("HeaderTelephoneAddress_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как English Version.
        /// </summary>
        internal static string LanguageSelector {
            get {
                return ResourceManager.GetString("LanguageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Выйти.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Образовательная программа.
        /// </summary>
        internal static string ObrazProgram {
            get {
                return ResourceManager.GetString("ObrazProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Личный кабинет поступающего.
        /// </summary>
        internal static string PersonalOfficeHeaderName {
            get {
                return ResourceManager.GetString("PersonalOfficeHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Личный кабинет поступающего в аспирантуру.
        /// </summary>
        internal static string PersonalOfficeHeaderName_Aspirant {
            get {
                return ResourceManager.GetString("PersonalOfficeHeaderName_Aspirant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Личный кабинет поступающего для иностранных граждан.
        /// </summary>
        internal static string PersonalOfficeHeaderName_Foreign {
            get {
                return ResourceManager.GetString("PersonalOfficeHeaderName_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Личный кабинет поступающего в колледж.
        /// </summary>
        internal static string PersonalOfficeHeaderName_SPO {
            get {
                return ResourceManager.GetString("PersonalOfficeHeaderName_SPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Направление.
        /// </summary>
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Сайт СПбГУ.
        /// </summary>
        internal static string SiteSpbu_Name {
            get {
                return ResourceManager.GetString("SiteSpbu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Университетская наб. д. 9.
        /// </summary>
        internal static string SpbuHeaderAddress {
            get {
                return ResourceManager.GetString("SpbuHeaderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Волховский пер, д.3.
        /// </summary>
        internal static string SpbuHeaderAddress_Foreign {
            get {
                return ResourceManager.GetString("SpbuHeaderAddress_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Санкт-Петербургский Государственный Университет.
        /// </summary>
        internal static string Spbu_Title {
            get {
                return ResourceManager.GetString("Spbu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Профиль.
        /// </summary>
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Выбор формата поступления.
        /// </summary>
        internal static string StartPageNav {
            get {
                return ResourceManager.GetString("StartPageNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Основа обучения.
        /// </summary>
        internal static string StudyBasis {
            get {
                return ResourceManager.GetString("StudyBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Госбюджетная.
        /// </summary>
        internal static string StudyBasisBudget {
            get {
                return ResourceManager.GetString("StudyBasisBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Форма обучения.
        /// </summary>
        internal static string StudyForm {
            get {
                return ResourceManager.GetString("StudyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Очная.
        /// </summary>
        internal static string StudyFormFullTime {
            get {
                return ResourceManager.GetString("StudyFormFullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Просмотр.
        /// </summary>
        internal static string txtShow {
            get {
                return ResourceManager.GetString("txtShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Просмотр заявления.
        /// </summary>
        internal static string txtShowHeader {
            get {
                return ResourceManager.GetString("txtShowHeader", resourceCulture);
            }
        }
    }
}
