//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Communication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Communication() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Communication", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Абитуриент.
        /// </summary>
        internal static string ApplicationCard {
            get {
                return ResourceManager.GetString("ApplicationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат к списку.
        /// </summary>
        internal static string BackToOverview {
            get {
                return ResourceManager.GetString("BackToOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный пакет документов.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резюме.
        /// </summary>
        internal static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервью (De).
        /// </summary>
        internal static string DeInterviewPts {
            get {
                return ResourceManager.GetString("DeInterviewPts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приглашение (De).
        /// </summary>
        internal static string DeInvitation {
            get {
                return ResourceManager.GetString("DeInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потфолио (De).
        /// </summary>
        internal static string DePortfolioPts {
            get {
                return ResourceManager.GetString("DePortfolioPts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диплом об образовании.
        /// </summary>
        internal static string Diploma {
            get {
                return ResourceManager.GetString("Diploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сертификаты ин.яз..
        /// </summary>
        internal static string EnglishCertificates {
            get {
                return ResourceManager.GetString("EnglishCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бюджет.
        /// </summary>
        internal static string HasFee {
            get {
                return ResourceManager.GetString("HasFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договор.
        /// </summary>
        internal static string HasNoFee {
            get {
                return ResourceManager.GetString("HasNoFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервью.
        /// </summary>
        internal static string Interview {
            get {
                return ResourceManager.GetString("Interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мотивационное письмо.
        /// </summary>
        internal static string MotivationLetter {
            get {
                return ResourceManager.GetString("MotivationLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гражданство.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет загруженных файлов.
        /// </summary>
        internal static string NoFiles {
            get {
                return ResourceManager.GetString("NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото не найдено.
        /// </summary>
        internal static string NoPhoto {
            get {
                return ResourceManager.GetString("NoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общий балл.
        /// </summary>
        internal static string OverallPts {
            get {
                return ResourceManager.GetString("OverallPts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скан паспорта.
        /// </summary>
        internal static string PassportScan {
            get {
                return ResourceManager.GetString("PassportScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок действия паспорта.
        /// </summary>
        internal static string PassportValid {
            get {
                return ResourceManager.GetString("PassportValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место рождения.
        /// </summary>
        internal static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        internal static string PosstalAddress {
            get {
                return ResourceManager.GetString("PosstalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распечатать анкету.
        /// </summary>
        internal static string PrintResults {
            get {
                return ResourceManager.GetString("PrintResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервью (Ru).
        /// </summary>
        internal static string RuInterviewPts {
            get {
                return ResourceManager.GetString("RuInterviewPts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приглашение (Ru).
        /// </summary>
        internal static string RuInvitation {
            get {
                return ResourceManager.GetString("RuInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Портфолио (Ru).
        /// </summary>
        internal static string RuPortfolioPts {
            get {
                return ResourceManager.GetString("RuPortfolioPts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        internal static string Statisctics {
            get {
                return ResourceManager.GetString("Statisctics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус анкеты.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виза.
        /// </summary>
        internal static string VisaApplicationPlace {
            get {
                return ResourceManager.GetString("VisaApplicationPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
