//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень.
        /// </summary>
        internal static string AppLevel {
            get {
                return ResourceManager.GetString("AppLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр заявлений.
        /// </summary>
        internal static string AppView {
            get {
                return ResourceManager.GetString("AppView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студгородок СПбГУ.
        /// </summary>
        internal static string CampusLink {
            get {
                return ResourceManager.GetString("CampusLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация для иностранцев.
        /// </summary>
        internal static string ForeigersInfoLink {
            get {
                return ResourceManager.GetString("ForeigersInfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поданные заявления.
        /// </summary>
        internal static string HeaderActiveApps {
            get {
                return ResourceManager.GetString("HeaderActiveApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Apps.
        /// </summary>
        internal static string HeaderCancelledApps {
            get {
                return ResourceManager.GetString("HeaderCancelledApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Нет поданных заявлений. &lt;a href=&quot;../../Abiturient/NewApplication&quot;&gt;Подать заявление&lt;/a&gt;.
        /// </summary>
        internal static string HeaderNoActiveApps {
            get {
                return ResourceManager.GetString("HeaderNoActiveApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Нет отозванных заявлений..
        /// </summary>
        internal static string HeaderNoCancelledApps {
            get {
                return ResourceManager.GetString("HeaderNoCancelledApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string InformationHeader {
            get {
                return ResourceManager.GetString("InformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string LinkApplicationInfo {
            get {
                return ResourceManager.GetString("LinkApplicationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дни открытых дверей образовательных программ магистратуры.
        /// </summary>
        internal static string MagOpenDoorsDaysLink {
            get {
                return ResourceManager.GetString("MagOpenDoorsDaysLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог образовательных программ (на русском).
        /// </summary>
        internal static string ObrazProgramCatalogLink {
            get {
                return ResourceManager.GetString("ObrazProgramCatalogLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог образовательных программ (на английском).
        /// </summary>
        internal static string ObrazProgramCatalogLinkEn {
            get {
                return ResourceManager.GetString("ObrazProgramCatalogLinkEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        internal static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет.
        /// </summary>
        internal static string PersonalOfficeHeader {
            get {
                return ResourceManager.GetString("PersonalOfficeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать.
        /// </summary>
        internal static string ShowApplication {
            get {
                return ResourceManager.GetString("ShowApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это главная страница вашего &lt;b&gt;Личного Кабинета&lt;/b&gt;. Сейчас можете подать заявление, изменить приоритеты уже существующих. Перейдя на страницу заявления, вы можете добавить сканы документов в ваше портфолио, создать мотивационное письмо и отозвать заявление..
        /// </summary>
        internal static string TitleInfo {
            get {
                return ResourceManager.GetString("TitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
