//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NewApplication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewApplication() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NewApplication", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаемый абитуриент. Используя кнопку «Добавить» укажите &lt;b&gt;все&lt;/b&gt; направления подготовки, образовательные программы, формы и основы обучения, в конкурсе по которым Вы собираетесь принять участие.&lt;br&gt;После добавления одного конкурса, Вам будет доступно добавление следующего..
        /// </summary>
        internal static string AbitMessage {
            get {
                return ResourceManager.GetString("AbitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экзамен по выбору.
        /// </summary>
        internal static string AGExams {
            get {
                return ResourceManager.GetString("AGExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите направление подготовки.
        /// </summary>
        internal static string AGHeaderProgram {
            get {
                return ResourceManager.GetString("AGHeaderProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string AGProfile {
            get {
                return ResourceManager.GetString("AGProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление.
        /// </summary>
        internal static string AGProgram {
            get {
                return ResourceManager.GetString("AGProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специализация.
        /// </summary>
        internal static string AGSpecialization {
            get {
                return ResourceManager.GetString("AGSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прием закрыт.
        /// </summary>
        internal static string AG_PriemClosed {
            get {
                return ResourceManager.GetString("AG_PriemClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень.
        /// </summary>
        internal static string ApplicationLevel {
            get {
                return ResourceManager.GetString("ApplicationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поданные заявления.
        /// </summary>
        internal static string ApplicationList {
            get {
                return ResourceManager.GetString("ApplicationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр заявлений.
        /// </summary>
        internal static string ApplicationView {
            get {
                return ResourceManager.GetString("ApplicationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факультет.
        /// </summary>
        internal static string BlockData_Faculty {
            get {
                return ResourceManager.GetString("BlockData_Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гослиния.
        /// </summary>
        internal static string BlockData_GosLine {
            get {
                return ResourceManager.GetString("BlockData_GosLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крым.
        /// </summary>
        internal static string BlockData_IsCrimea {
            get {
                return ResourceManager.GetString("BlockData_IsCrimea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иностранный конкурс/Гослиния.
        /// </summary>
        internal static string BlockData_IsForeign {
            get {
                return ResourceManager.GetString("BlockData_IsForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление.
        /// </summary>
        internal static string BlockData_LicenseProgram {
            get {
                return ResourceManager.GetString("BlockData_LicenseProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string BlockData_MagSpecialization {
            get {
                return ResourceManager.GetString("BlockData_MagSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образовательная программа.
        /// </summary>
        internal static string BlockData_ObrazProgram {
            get {
                return ResourceManager.GetString("BlockData_ObrazProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string BlockData_Specialization {
            get {
                return ResourceManager.GetString("BlockData_Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основа обучения.
        /// </summary>
        internal static string BlockData_StudyBasis {
            get {
                return ResourceManager.GetString("BlockData_StudyBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма обучения.
        /// </summary>
        internal static string BlockData_StudyForm {
            get {
                return ResourceManager.GetString("BlockData_StudyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать заявление.
        /// </summary>
        internal static string btnCreateApp {
            get {
                return ResourceManager.GetString("btnCreateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нуждаюсь в общежитии на время обучения.
        /// </summary>
        internal static string chbNeedHostel {
            get {
                return ResourceManager.GetString("chbNeedHostel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы закончили: .
        /// </summary>
        internal static string Educ_Mes1 {
            get {
                return ResourceManager.GetString("Educ_Mes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам доступны следующие возможности.
        /// </summary>
        internal static string Educ_Mes2 {
            get {
                return ResourceManager.GetString("Educ_Mes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поступать по конкурсу для лиц, постоянно проживающих в Крыму.
        /// </summary>
        internal static string EnterCrimea {
            get {
                return ResourceManager.GetString("EnterCrimea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поступать по конкурсу для иностранцев/гослинии.
        /// </summary>
        internal static string EnterGosLine {
            get {
                return ResourceManager.GetString("EnterGosLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление уже подавалось.
        /// </summary>
        internal static string ErrorHasApplication {
            get {
                return ResourceManager.GetString("ErrorHasApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите факультет.
        /// </summary>
        internal static string HeaderFaculty {
            get {
                return ResourceManager.GetString("HeaderFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласно данным анкеты, вы поступаете на.
        /// </summary>
        internal static string HeaderFirstCourse_1 {
            get {
                return ResourceManager.GetString("HeaderFirstCourse_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to первый курс.
        /// </summary>
        internal static string HeaderFirstCourse_2 {
            get {
                return ResourceManager.GetString("HeaderFirstCourse_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите профиль.
        /// </summary>
        internal static string HeaderMagProfile {
            get {
                return ResourceManager.GetString("HeaderMagProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите образовательную программу.
        /// </summary>
        internal static string HeaderObrazProgram {
            get {
                return ResourceManager.GetString("HeaderObrazProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень, который вы желаете получить:.
        /// </summary>
        internal static string HeaderObtainingLevel {
            get {
                return ResourceManager.GetString("HeaderObtainingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите направление.
        /// </summary>
        internal static string HeaderProfession {
            get {
                return ResourceManager.GetString("HeaderProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите профиль.
        /// </summary>
        internal static string HeaderProfile {
            get {
                return ResourceManager.GetString("HeaderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параллельное обучение.
        /// </summary>
        internal static string IsParallel {
            get {
                return ResourceManager.GetString("IsParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сокращенные программы.
        /// </summary>
        internal static string IsReduced {
            get {
                return ResourceManager.GetString("IsReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для лиц, имеющих ВО.
        /// </summary>
        internal static string IsSecond {
            get {
                return ResourceManager.GetString("IsSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неоднозначный выбор учебного плана.
        /// </summary>
        internal static string NewApp_2MoreEntry {
            get {
                return ResourceManager.GetString("NewApp_2MoreEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление уже подано на 3 направления.
        /// </summary>
        internal static string NewApp_3MorePrograms {
            get {
                return ResourceManager.GetString("NewApp_3MorePrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приём заявлений на данное направление закрыт..
        /// </summary>
        internal static string NewApp_ClosedEntry {
            get {
                return ResourceManager.GetString("NewApp_ClosedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при удалении заявления.
        /// </summary>
        internal static string NewApp_DeleteApp_Fail {
            get {
                return ResourceManager.GetString("NewApp_DeleteApp_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя удалить уже подтверждённое заявление!.
        /// </summary>
        internal static string NewApp_FailDeleteApp_IsCommited {
            get {
                return ResourceManager.GetString("NewApp_FailDeleteApp_IsCommited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление на данную программу уже подано.
        /// </summary>
        internal static string NewApp_HasApplicationOnEntry {
            get {
                return ResourceManager.GetString("NewApp_HasApplicationOnEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден учебный план.
        /// </summary>
        internal static string NewApp_NoEntry {
            get {
                return ResourceManager.GetString("NewApp_NoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет доступных направлений для подачи заявления.
        /// </summary>
        internal static string NewApp_NoFreeEntries {
            get {
                return ResourceManager.GetString("NewApp_NoFreeEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приём заявлений на данное направление ещё не открыт..
        /// </summary>
        internal static string NewApp_NotOpenedEntry {
            get {
                return ResourceManager.GetString("NewApp_NotOpenedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет поданых заявлений.
        /// </summary>
        internal static string NoApplications {
            get {
                return ResourceManager.GetString("NoApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое заявление.
        /// </summary>
        internal static string PageSubheader {
            get {
                return ResourceManager.GetString("PageSubheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание нового заявления.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аспирантура.
        /// </summary>
        internal static string Select_Aspirantura {
            get {
                return ResourceManager.GetString("Select_Aspirantura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первый курс.
        /// </summary>
        internal static string Select_FirstCourse {
            get {
                return ResourceManager.GetString("Select_FirstCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магистратура.
        /// </summary>
        internal static string Select_Magistery {
            get {
                return ResourceManager.GetString("Select_Magistery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Госбюджетная.
        /// </summary>
        internal static string Select_StudyBasis1 {
            get {
                return ResourceManager.GetString("Select_StudyBasis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договорная.
        /// </summary>
        internal static string Select_StudyBasis2 {
            get {
                return ResourceManager.GetString("Select_StudyBasis2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневная.
        /// </summary>
        internal static string Select_StudyForm1 {
            get {
                return ResourceManager.GetString("Select_StudyForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вечерняя.
        /// </summary>
        internal static string Select_StudyForm2 {
            get {
                return ResourceManager.GetString("Select_StudyForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семестр.
        /// </summary>
        internal static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите основу обучения.
        /// </summary>
        internal static string StudyBasis {
            get {
                return ResourceManager.GetString("StudyBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите форму обучения.
        /// </summary>
        internal static string StudyForm {
            get {
                return ResourceManager.GetString("StudyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
