//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PersonStartPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonStartPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PersonStartPage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поступление на 1 курс (бакалавриат, специалитет).
        /// </summary>
        internal static string AbiturientType1 {
            get {
                return ResourceManager.GetString("AbiturientType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поступление в аспирантуру.
        /// </summary>
        internal static string AbiturientType10 {
            get {
                return ResourceManager.GetString("AbiturientType10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поступление в ординатуру.
        /// </summary>
        internal static string AbiturientType11 {
            get {
                return ResourceManager.GetString("AbiturientType11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поступление в магистратуру.
        /// </summary>
        internal static string AbiturientType2 {
            get {
                return ResourceManager.GetString("AbiturientType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод с платной основы обучения на бюджетную.
        /// </summary>
        internal static string AbiturientType3 {
            get {
                return ResourceManager.GetString("AbiturientType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод в СПбГУ.
        /// </summary>
        internal static string AbiturientType4 {
            get {
                return ResourceManager.GetString("AbiturientType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление в СПбГУ.
        /// </summary>
        internal static string AbiturientType5 {
            get {
                return ResourceManager.GetString("AbiturientType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение формы обучения.
        /// </summary>
        internal static string AbiturientType6 {
            get {
                return ResourceManager.GetString("AbiturientType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смена образовательной программы.
        /// </summary>
        internal static string AbiturientType7 {
            get {
                return ResourceManager.GetString("AbiturientType7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поступление в Академическую Гимназию.
        /// </summary>
        internal static string AbiturientType8 {
            get {
                return ResourceManager.GetString("AbiturientType8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поступление на программы среднего профессионального образования.
        /// </summary>
        internal static string AbiturientType9 {
            get {
                return ResourceManager.GetString("AbiturientType9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите направление для поступления.
        /// </summary>
        internal static string AppSelectHeader {
            get {
                return ResourceManager.GetString("AppSelectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите действие, которое вы хотите совершить в Личном Кабинете.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
    }
}
