//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PersonalOffice_Step6 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonalOffice_Step6() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PersonalOffice_Step6", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Закончить регистрацию.
        /// </summary>
        internal static string btnValue_EndRegisration {
            get {
                return ResourceManager.GetString("btnValue_EndRegisration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Лицо, с которым можно связаться в экстренных случаях:.
        /// </summary>
        internal static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как (указать Ф.И.О., степень родства, телефон, моб.телефон, эл.почта).
        /// </summary>
        internal static string ContactPerson_SubHeader {
            get {
                return ResourceManager.GetString("ContactPerson_SubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Способ возврата поданых документов.
        /// </summary>
        internal static string DocumentsReturn {
            get {
                return ResourceManager.GetString("DocumentsReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как О себе дополнительно сообщаю:.
        /// </summary>
        internal static string ExtraInfo {
            get {
                return ResourceManager.GetString("ExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Я подтверждаю, что предоставленная мной информация корректна и достоверна. Даю согласие на обработку предоставленных персональных данных в порядке, установленном Федеральным законом от 27 июля 2006 года № 152-ФЗ «О персональных данных»..
        /// </summary>
        internal static string FZ152_Header {
            get {
                return ResourceManager.GetString("FZ152_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Подтверждаю и согласен.
        /// </summary>
        internal static string FZ_152Agree {
            get {
                return ResourceManager.GetString("FZ_152Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вы должны принять условия.
        /// </summary>
        internal static string FZ_152_Message {
            get {
                return ResourceManager.GetString("FZ_152_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Нуждаюсь в общежитии на время поступления.
        /// </summary>
        internal static string HostelAbit {
            get {
                return ResourceManager.GetString("HostelAbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Нуждаюсь в общежитии на время обучения.
        /// </summary>
        internal static string HostelEduc {
            get {
                return ResourceManager.GetString("HostelEduc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Общежитие.
        /// </summary>
        internal static string HostelHeader {
            get {
                return ResourceManager.GetString("HostelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Особые условия.
        /// </summary>
        internal static string NeedSpecialConditions {
            get {
                return ResourceManager.GetString("NeedSpecialConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Нуждаюсь в создании особых условий при прохождении вступительных испытаний.
        /// </summary>
        internal static string NeedSpecialConditionsFull {
            get {
                return ResourceManager.GetString("NeedSpecialConditionsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Опыт работы.
        /// </summary>
        internal static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Лицо, с которым можно связаться в экстренных случаях:.
        /// </summary>
        internal static string ParentsHeader {
            get {
                return ResourceManager.GetString("ParentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Родители и льготы.
        /// </summary>
        internal static string ParentsPageHeader {
            get {
                return ResourceManager.GetString("ParentsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Email.
        /// </summary>
        internal static string Parent_Email {
            get {
                return ResourceManager.GetString("Parent_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Имя.
        /// </summary>
        internal static string Parent_Name {
            get {
                return ResourceManager.GetString("Parent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Телефон.
        /// </summary>
        internal static string Parent_Phone {
            get {
                return ResourceManager.GetString("Parent_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Отчество.
        /// </summary>
        internal static string Parent_SecondName {
            get {
                return ResourceManager.GetString("Parent_SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Фамилия.
        /// </summary>
        internal static string Parent_Surname {
            get {
                return ResourceManager.GetString("Parent_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Родители (законные представители).
        /// </summary>
        internal static string Parent_Title {
            get {
                return ResourceManager.GetString("Parent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Место работы.
        /// </summary>
        internal static string Parent_Work {
            get {
                return ResourceManager.GetString("Parent_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Должность.
        /// </summary>
        internal static string Parent_WorkPosition {
            get {
                return ResourceManager.GetString("Parent_WorkPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Право на льготы:.
        /// </summary>
        internal static string Privileges {
            get {
                return ResourceManager.GetString("Privileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Претендую на льготы (инвалид I,II ст., участник боевых действий, сирота, чернобылец...).
        /// </summary>
        internal static string PrivilegesFull {
            get {
                return ResourceManager.GetString("PrivilegesFull", resourceCulture);
            }
        }
    }
}
