//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PersonStartPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonStartPage() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PersonStartPage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Поступление на 1 курс (бакалавриат, специалитет).
        /// </summary>
        internal static string AbiturientType1 {
            get {
                return ResourceManager.GetString("AbiturientType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Поступление в аспирантуру.
        /// </summary>
        internal static string AbiturientType10 {
            get {
                return ResourceManager.GetString("AbiturientType10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Поступление в ординатуру.
        /// </summary>
        internal static string AbiturientType11 {
            get {
                return ResourceManager.GetString("AbiturientType11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Поступление в магистратуру.
        /// </summary>
        internal static string AbiturientType2 {
            get {
                return ResourceManager.GetString("AbiturientType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Перевод с платной основы обучения на бюджетную.
        /// </summary>
        internal static string AbiturientType3 {
            get {
                return ResourceManager.GetString("AbiturientType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Перевод в СПбГУ.
        /// </summary>
        internal static string AbiturientType4 {
            get {
                return ResourceManager.GetString("AbiturientType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Восстановление в СПбГУ.
        /// </summary>
        internal static string AbiturientType5 {
            get {
                return ResourceManager.GetString("AbiturientType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Изменение формы обучения.
        /// </summary>
        internal static string AbiturientType6 {
            get {
                return ResourceManager.GetString("AbiturientType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Смена образовательной программы.
        /// </summary>
        internal static string AbiturientType7 {
            get {
                return ResourceManager.GetString("AbiturientType7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Поступление в Академическую Гимназию.
        /// </summary>
        internal static string AbiturientType8 {
            get {
                return ResourceManager.GetString("AbiturientType8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Поступление на программы среднего профессионального образования.
        /// </summary>
        internal static string AbiturientType9 {
            get {
                return ResourceManager.GetString("AbiturientType9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Выберите направление для поступления.
        /// </summary>
        internal static string AppSelectHeader {
            get {
                return ResourceManager.GetString("AppSelectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Выберите действие, которое вы хотите совершить в Личном Кабинете.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
    }
}
