//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PersonalOffice_Step4 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonalOffice_Step4() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PersonalOffice_Step4", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата аккредитации.
        /// </summary>
        internal static string AccreditationDate {
            get {
                return ResourceManager.GetString("AccreditationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер аккредитации.
        /// </summary>
        internal static string AccreditationNumber {
            get {
                return ResourceManager.GetString("AccreditationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить оценку.
        /// </summary>
        internal static string AddMark {
            get {
                return ResourceManager.GetString("AddMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион (для российских аттестатов).
        /// </summary>
        internal static string AttestatRegion {
            get {
                return ResourceManager.GetString("AttestatRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите номер региона.
        /// </summary>
        internal static string AttestatRegion_Message {
            get {
                return ResourceManager.GetString("AttestatRegion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средний балл.
        /// </summary>
        internal static string AvgMark {
            get {
                return ResourceManager.GetString("AvgMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для смены основы обучения, укажите причину:.
        /// </summary>
        internal static string ChangeStudyFormReason {
            get {
                return ResourceManager.GetString("ChangeStudyFormReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна обучения.
        /// </summary>
        internal static string CountryCurEducId {
            get {
                return ResourceManager.GetString("CountryCurEducId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна, в которой получено предыдущее образование.
        /// </summary>
        internal static string CountryEducId {
            get {
                return ResourceManager.GetString("CountryEducId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее образование.
        /// </summary>
        internal static string CurrentEducationHeader {
            get {
                return ResourceManager.GetString("CurrentEducationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите направление.
        /// </summary>
        internal static string CurrentEducation_LicenseProgramId_Message {
            get {
                return ResourceManager.GetString("CurrentEducation_LicenseProgramId_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите образовательную программу.
        /// </summary>
        internal static string CurrentEducation_ObrazProgramId_Message {
            get {
                return ResourceManager.GetString("CurrentEducation_ObrazProgramId_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее направление (специальность).
        /// </summary>
        internal static string CurrentLicenceProgram {
            get {
                return ResourceManager.GetString("CurrentLicenceProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая образовательная программа.
        /// </summary>
        internal static string CurrentObrazProgram {
            get {
                return ResourceManager.GetString("CurrentObrazProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий профиль (специализация).
        /// </summary>
        internal static string CurrentProfile {
            get {
                return ResourceManager.GetString("CurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без номера.
        /// </summary>
        internal static string CurrentYear {
            get {
                return ResourceManager.GetString("CurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        internal static string DiplomNumber {
            get {
                return ResourceManager.GetString("DiplomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите номер документа.
        /// </summary>
        internal static string DiplomNumber_Message {
            get {
                return ResourceManager.GetString("DiplomNumber_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серия.
        /// </summary>
        internal static string DiplomSeries {
            get {
                return ResourceManager.GetString("DiplomSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите серию документа.
        /// </summary>
        internal static string DiplomSeries_Message {
            get {
                return ResourceManager.GetString("DiplomSeries_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема дипломной работы.
        /// </summary>
        internal static string DiplomTheme {
            get {
                return ResourceManager.GetString("DiplomTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные об отчислении из СПбГУ.
        /// </summary>
        internal static string DisorderInfo {
            get {
                return ResourceManager.GetString("DisorderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год отчисления.
        /// </summary>
        internal static string DisorderYear {
            get {
                return ResourceManager.GetString("DisorderYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить ещё.
        /// </summary>
        internal static string EducationBlockAdd {
            get {
                return ResourceManager.GetString("EducationBlockAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string EducationBlockDelete {
            get {
                return ResourceManager.GetString("EducationBlockDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ об образовании.
        /// </summary>
        internal static string EducationDocumentHeader {
            get {
                return ResourceManager.GetString("EducationDocumentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите только те документы, оригиналы которых Вы должны предоставить при зачислении.
        /// </summary>
        internal static string EducationDocumentsHeader {
            get {
                return ResourceManager.GetString("EducationDocumentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные об образовании.
        /// </summary>
        internal static string EducationHeader {
            get {
                return ResourceManager.GetString("EducationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить еще.
        /// </summary>
        internal static string EducationInfo_AddOne {
            get {
                return ResourceManager.GetString("EducationInfo_AddOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string EducationInfo_Delete {
            get {
                return ResourceManager.GetString("EducationInfo_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите год в 4-значном формате.
        /// </summary>
        internal static string EducationInfo_SchoolExitYear_MessageFormat {
            get {
                return ResourceManager.GetString("EducationInfo_SchoolExitYear_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите название образовательного учреждения.
        /// </summary>
        internal static string EducationInfo_SchoolName_Message {
            get {
                return ResourceManager.GetString("EducationInfo_SchoolName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Балл.
        /// </summary>
        internal static string EGEball {
            get {
                return ResourceManager.GetString("EGEball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баллы ЕГЭ.
        /// </summary>
        internal static string EGEmarks {
            get {
                return ResourceManager.GetString("EGEmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет баллов по ЕГЭ.
        /// </summary>
        internal static string EGEnomarks {
            get {
                return ResourceManager.GetString("EGEnomarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер сертификата.
        /// </summary>
        internal static string EGEsert {
            get {
                return ResourceManager.GetString("EGEsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предмет.
        /// </summary>
        internal static string EGEsubject {
            get {
                return ResourceManager.GetString("EGEsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год.
        /// </summary>
        internal static string EGEyear {
            get {
                return ResourceManager.GetString("EGEyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итоговая оценка по английскому языку (если изучался).
        /// </summary>
        internal static string EnglishMark {
            get {
                return ResourceManager.GetString("EnglishMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желаю изучать английский в СПбГУ &apos;с нуля&apos;.
        /// </summary>
        internal static string EnglishNull {
            get {
                return ResourceManager.GetString("EnglishNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер свидетельства.
        /// </summary>
        internal static string EqualityDocumentNumber {
            get {
                return ResourceManager.GetString("EqualityDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имеет гос. аккредитацию.
        /// </summary>
        internal static string HasAccreditation {
            get {
                return ResourceManager.GetString("HasAccreditation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получаю академическую стипендию.
        /// </summary>
        internal static string HasScholarship {
            get {
                return ResourceManager.GetString("HasScholarship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имею сертификат ТРКИ.
        /// </summary>
        internal static string HasTRKI {
            get {
                return ResourceManager.GetString("HasTRKI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сведения о текущем месте обучения.
        /// </summary>
        internal static string Header_CurrentEducation {
            get {
                return ResourceManager.GetString("Header_CurrentEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные о высшем образовании.
        /// </summary>
        internal static string HEDataHeader {
            get {
                return ResourceManager.GetString("HEDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год начала обучения.
        /// </summary>
        internal static string HEEntryYear {
            get {
                return ResourceManager.GetString("HEEntryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свидетельство об эквивалентности.
        /// </summary>
        internal static string IsEqual {
            get {
                return ResourceManager.GetString("IsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иностранный язык для вступительного испытания.
        /// </summary>
        internal static string LanguageId {
            get {
                return ResourceManager.GetString("LanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название образовательной программы.
        /// </summary>
        internal static string ObrazProgramName {
            get {
                return ResourceManager.GetString("ObrazProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сдаю в СПбГУ.
        /// </summary>
        internal static string PassInSPbSU {
            get {
                return ResourceManager.GetString("PassInSPbSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квалификация.
        /// </summary>
        internal static string PersonQualification {
            get {
                return ResourceManager.GetString("PersonQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление (специальность).
        /// </summary>
        internal static string PersonSpecialization {
            get {
                return ResourceManager.GetString("PersonSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основа обучения.
        /// </summary>
        internal static string PersonStudyBasis {
            get {
                return ResourceManager.GetString("PersonStudyBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма обучения.
        /// </summary>
        internal static string PersonStudyForm {
            get {
                return ResourceManager.GetString("PersonStudyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень обучения.
        /// </summary>
        internal static string PersonStudyLevel {
            get {
                return ResourceManager.GetString("PersonStudyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семестр.
        /// </summary>
        internal static string PersonStudySemester {
            get {
                return ResourceManager.GetString("PersonStudySemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстанавливаюсь для ИГА.
        /// </summary>
        internal static string RecoverForIGA {
            get {
                return ResourceManager.GetString("RecoverForIGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медалист (красный диплом).
        /// </summary>
        internal static string RedDiploma {
            get {
                return ResourceManager.GetString("RedDiploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите регион.
        /// </summary>
        internal static string RegionEducId {
            get {
                return ResourceManager.GetString("RegionEducId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Населенный пункт.
        /// </summary>
        internal static string ResidentialPlace {
            get {
                return ResourceManager.GetString("ResidentialPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес школы.
        /// </summary>
        internal static string SchoolAddress {
            get {
                return ResourceManager.GetString("SchoolAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название текущего образовательного учреждения.
        /// </summary>
        internal static string SchoolCurName {
            get {
                return ResourceManager.GetString("SchoolCurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оконченный класс.
        /// </summary>
        internal static string SchoolExitClass {
            get {
                return ResourceManager.GetString("SchoolExitClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год окончания обучения.
        /// </summary>
        internal static string SchoolExitYear {
            get {
                return ResourceManager.GetString("SchoolExitYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите год окончания обучения.
        /// </summary>
        internal static string SchoolExitYear_Message {
            get {
                return ResourceManager.GetString("SchoolExitYear_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название образовательного учреждения.
        /// </summary>
        internal static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер школы.
        /// </summary>
        internal static string SchoolNumber {
            get {
                return ResourceManager.GetString("SchoolNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип образовательного учреждения.
        /// </summary>
        internal static string SchoolTypeId {
            get {
                return ResourceManager.GetString("SchoolTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сдаю во &quot;второй волне&quot;.
        /// </summary>
        internal static string SecondWave {
            get {
                return ResourceManager.GetString("SecondWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер сертификата ТРКИ.
        /// </summary>
        internal static string TRKICertificateNumber {
            get {
                return ResourceManager.GetString("TRKICertificateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип поступления.
        /// </summary>
        internal static string VuzAdditionalTypeId {
            get {
                return ResourceManager.GetString("VuzAdditionalTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год предполагаемого окончания обучения.
        /// </summary>
        internal static string VuzExitYear {
            get {
                return ResourceManager.GetString("VuzExitYear", resourceCulture);
            }
        }
    }
}
