//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PersonalOffice_Step5 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonalOffice_Step5() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PersonalOffice_Step5", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Добавить.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Удалить.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Добавленные сертификаты.
        /// </summary>
        internal static string CertificateAdded {
            get {
                return ResourceManager.GetString("CertificateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Языковые сертификаты.
        /// </summary>
        internal static string CertificateHeader {
            get {
                return ResourceManager.GetString("CertificateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Номер сертификата.
        /// </summary>
        internal static string CertificateNumber {
            get {
                return ResourceManager.GetString("CertificateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как пройден.
        /// </summary>
        internal static string CertificatePassed {
            get {
                return ResourceManager.GetString("CertificatePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Тип сертификата.
        /// </summary>
        internal static string CertificateType {
            get {
                return ResourceManager.GetString("CertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Количество баллов.
        /// </summary>
        internal static string CertificateValue {
            get {
                return ResourceManager.GetString("CertificateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Дата.
        /// </summary>
        internal static string DocumentDate {
            get {
                return ResourceManager.GetString("DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите дату.
        /// </summary>
        internal static string DocumentDateMessage {
            get {
                return ResourceManager.GetString("DocumentDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Документ.
        /// </summary>
        internal static string DocumentHeader {
            get {
                return ResourceManager.GetString("DocumentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Номер.
        /// </summary>
        internal static string DocumentNumber {
            get {
                return ResourceManager.GetString("DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите номер (в случае отсутствия поставьте прочерк).
        /// </summary>
        internal static string DocumentNumberMessage {
            get {
                return ResourceManager.GetString("DocumentNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Серия.
        /// </summary>
        internal static string DocumentSeries {
            get {
                return ResourceManager.GetString("DocumentSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите серию (в случае отсутствия поставьте прочерк).
        /// </summary>
        internal static string DocumentSeriesMessage {
            get {
                return ResourceManager.GetString("DocumentSeriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Сюда вы можете прикрепить сканы языковых сертификатов&lt;/br&gt;
        ///Остальные документы можно прикрепить в окне Общие документы. &lt;/br&gt;.
        /// </summary>
        internal static string EnglishCertificatesLoad {
            get {
                return ResourceManager.GetString("EnglishCertificatesLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Стаж (полных лет).
        /// </summary>
        internal static string JobExperience {
            get {
                return ResourceManager.GetString("JobExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Должностные обязанности.
        /// </summary>
        internal static string JobFunctions {
            get {
                return ResourceManager.GetString("JobFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Место работы(практики).
        /// </summary>
        internal static string JobLocation {
            get {
                return ResourceManager.GetString("JobLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Должность.
        /// </summary>
        internal static string JobPosition {
            get {
                return ResourceManager.GetString("JobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как нет.
        /// </summary>
        internal static string NoWorks {
            get {
                return ResourceManager.GetString("NoWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Добавленные олимпиады.
        /// </summary>
        internal static string OlympiadsAdded {
            get {
                return ResourceManager.GetString("OlympiadsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Документ.
        /// </summary>
        internal static string OlympiadsDocument {
            get {
                return ResourceManager.GetString("OlympiadsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Олимпиады.
        /// </summary>
        internal static string OlympiadsHeader {
            get {
                return ResourceManager.GetString("OlympiadsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Пожалуйста, не забудьте приложить копию(скан) документа, в разделе &quot;Общие документы&quot;.
        /// </summary>
        internal static string OlympiadsMessage {
            get {
                return ResourceManager.GetString("OlympiadsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Название.
        /// </summary>
        internal static string OlympiadsName {
            get {
                return ResourceManager.GetString("OlympiadsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Статус.
        /// </summary>
        internal static string OlympiadsStatus {
            get {
                return ResourceManager.GetString("OlympiadsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Предмет.
        /// </summary>
        internal static string OlympiadsSubject {
            get {
                return ResourceManager.GetString("OlympiadsSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Тип.
        /// </summary>
        internal static string OlympiadsType {
            get {
                return ResourceManager.GetString("OlympiadsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Год.
        /// </summary>
        internal static string OlympiadsYear {
            get {
                return ResourceManager.GetString("OlympiadsYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Дополнительные сведения.
        /// </summary>
        internal static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Загрузите сканы языковых сертификатов.
        /// </summary>
        internal static string PersonalOffice_Certificates {
            get {
                return ResourceManager.GetString("PersonalOffice_Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Участие в научно-исследовательской работе.
        /// </summary>
        internal static string ResearchWorkHeader {
            get {
                return ResourceManager.GetString("ResearchWorkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как                &lt;p&gt;Участие в научных конференциях (укажите тему конференции, дату и место ее проведения; тему доклада/выступления), опубликованные научные статьи, работа в научных лабораториях, работа в проектных группах.&lt;/p&gt;
        ///                &lt;p&gt;Напоминаем, что Вам необходимо предоставить документы, &lt;b&gt;подтверждающие:&lt;/b&gt; &lt;/p&gt;
        ///                &lt;ul&gt;
        ///                    &lt;li&gt;Ваше участие в конференциях, семинарах, круглых столах и прочих научных и научно-практических мероприятиях. В качестве таковых могут выст [остаток строки был усечен]&quot;;.
        /// </summary>
        internal static string ResearchWorkMessage {
            get {
                return ResourceManager.GetString("ResearchWorkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Текст.
        /// </summary>
        internal static string ScWorksText {
            get {
                return ResourceManager.GetString("ScWorksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Тип.
        /// </summary>
        internal static string ScWorksType {
            get {
                return ResourceManager.GetString("ScWorksType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Год.
        /// </summary>
        internal static string ScWorksYear {
            get {
                return ResourceManager.GetString("ScWorksYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Укажите необходимые сведения.
        /// </summary>
        internal static string ScWork_Message {
            get {
                return ResourceManager.GetString("ScWork_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Pазряд:.
        /// </summary>
        internal static string SportCategory {
            get {
                return ResourceManager.GetString("SportCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Спорт. квалификация:.
        /// </summary>
        internal static string SportQualification {
            get {
                return ResourceManager.GetString("SportQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Спорт. квалификация, разряд:.
        /// </summary>
        internal static string SportQualificationCategory {
            get {
                return ResourceManager.GetString("SportQualificationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Спортивные достижения.
        /// </summary>
        internal static string SportValue {
            get {
                return ResourceManager.GetString("SportValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите целое число.
        /// </summary>
        internal static string validationMsgCertValue {
            get {
                return ResourceManager.GetString("validationMsgCertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите должностные обязанности.
        /// </summary>
        internal static string validationMsgPersonWorksDuties {
            get {
                return ResourceManager.GetString("validationMsgPersonWorksDuties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите целое число.
        /// </summary>
        internal static string validationMsgPersonWorksExperience {
            get {
                return ResourceManager.GetString("validationMsgPersonWorksExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите должность.
        /// </summary>
        internal static string validationMsgPersonWorksLevel {
            get {
                return ResourceManager.GetString("validationMsgPersonWorksLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите место работы.
        /// </summary>
        internal static string validationMsgPersonWorksPlace {
            get {
                return ResourceManager.GetString("validationMsgPersonWorksPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Опыт работы (практики).
        /// </summary>
        internal static string WorkExperienceHeader {
            get {
                return ResourceManager.GetString("WorkExperienceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вид деятельности.
        /// </summary>
        internal static string WorkInfo {
            get {
                return ResourceManager.GetString("WorkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Год деятельности.
        /// </summary>
        internal static string WorkYear {
            get {
                return ResourceManager.GetString("WorkYear", resourceCulture);
            }
        }
    }
}
