//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PersonalOffice_Step3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonalOffice_Step3() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PersonalOffice_Step3", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        internal static string AdCity {
            get {
                return ResourceManager.GetString("AdCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительный Email.
        /// </summary>
        internal static string AddEmail {
            get {
                return ResourceManager.GetString("AddEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дополнительный Email.
        /// </summary>
        internal static string AddEmail_Message {
            get {
                return ResourceManager.GetString("AddEmail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес проживания/почтовый адрес (если отличается):.
        /// </summary>
        internal static string AdditionalAddress_Header {
            get {
                return ResourceManager.GetString("AdditionalAddress_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите адрес.
        /// </summary>
        internal static string AddressData_Message {
            get {
                return ResourceManager.GetString("AddressData_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить страну проживания Вы можете на странице &quot;Личные Данные&quot;.
        /// </summary>
        internal static string ChangeCountry_Title {
            get {
                return ResourceManager.GetString("ChangeCountry_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите город.
        /// </summary>
        internal static string City_Message {
            get {
                return ResourceManager.GetString("City_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        internal static string CountryId {
            get {
                return ResourceManager.GetString("CountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартира.
        /// </summary>
        internal static string Flat {
            get {
                return ResourceManager.GetString("Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дом.
        /// </summary>
        internal static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дом.
        /// </summary>
        internal static string House_Message {
            get {
                return ResourceManager.GetString("House_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корпус.
        /// </summary>
        internal static string Korpus {
            get {
                return ResourceManager.GetString("Korpus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основной телефон.
        /// </summary>
        internal static string MainPhone {
            get {
                return ResourceManager.GetString("MainPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите основной номер.
        /// </summary>
        internal static string MainPhone_Message {
            get {
                return ResourceManager.GetString("MainPhone_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактные телефоны:.
        /// </summary>
        internal static string PhonesHeader {
            get {
                return ResourceManager.GetString("PhonesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индекс.
        /// </summary>
        internal static string PostIndex {
            get {
                return ResourceManager.GetString("PostIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите индекс.
        /// </summary>
        internal static string PostIndex_Message {
            get {
                return ResourceManager.GetString("PostIndex_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найден другой почтовый индекс. Кликните для изменения.
        /// </summary>
        internal static string PostIndex_MessageFoundOtherIndex {
            get {
                return ResourceManager.GetString("PostIndex_MessageFoundOtherIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион.
        /// </summary>
        internal static string RegionId {
            get {
                return ResourceManager.GetString("RegionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес регистрации:.
        /// </summary>
        internal static string RegistrationHeader {
            get {
                return ResourceManager.GetString("RegistrationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительный.
        /// </summary>
        internal static string SecondPhone {
            get {
                return ResourceManager.GetString("SecondPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дополнительный номер .
        /// </summary>
        internal static string SecondPhone_Message {
            get {
                return ResourceManager.GetString("SecondPhone_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улица.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt; (микрорайон, квартал и пр.).
        /// </summary>
        internal static string Street_1 {
            get {
                return ResourceManager.GetString("Street_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите улицу.
        /// </summary>
        internal static string Street_Message {
            get {
                return ResourceManager.GetString("Street_Message", resourceCulture);
            }
        }
    }
}
