//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PersonalOffice_Step6 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonalOffice_Step6() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PersonalOffice_Step6", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закончить регистрацию.
        /// </summary>
        internal static string btnValue_EndRegisration {
            get {
                return ResourceManager.GetString("btnValue_EndRegisration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицо, с которым можно связаться в экстренных случаях:.
        /// </summary>
        internal static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (указать Ф.И.О., степень родства, телефон, моб.телефон, эл.почта).
        /// </summary>
        internal static string ContactPerson_SubHeader {
            get {
                return ResourceManager.GetString("ContactPerson_SubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способ возврата поданых документов.
        /// </summary>
        internal static string DocumentsReturn {
            get {
                return ResourceManager.GetString("DocumentsReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О себе дополнительно сообщаю:.
        /// </summary>
        internal static string ExtraInfo {
            get {
                return ResourceManager.GetString("ExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я подтверждаю, что предоставленная мной информация корректна и достоверна. Даю согласие на обработку предоставленных персональных данных в порядке, установленном Федеральным законом от 27 июля 2006 года № 152-ФЗ «О персональных данных»..
        /// </summary>
        internal static string FZ152_Header {
            get {
                return ResourceManager.GetString("FZ152_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждаю и согласен.
        /// </summary>
        internal static string FZ_152Agree {
            get {
                return ResourceManager.GetString("FZ_152Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны принять условия.
        /// </summary>
        internal static string FZ_152_Message {
            get {
                return ResourceManager.GetString("FZ_152_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нуждаюсь в общежитии на время поступления.
        /// </summary>
        internal static string HostelAbit {
            get {
                return ResourceManager.GetString("HostelAbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нуждаюсь в общежитии на время обучения.
        /// </summary>
        internal static string HostelEduc {
            get {
                return ResourceManager.GetString("HostelEduc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общежитие.
        /// </summary>
        internal static string HostelHeader {
            get {
                return ResourceManager.GetString("HostelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицо, с которым можно связаться в экстренных случаях:.
        /// </summary>
        internal static string ParentsHeader {
            get {
                return ResourceManager.GetString("ParentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Право на льготы:.
        /// </summary>
        internal static string Privileges {
            get {
                return ResourceManager.GetString("Privileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Претендую на льготы (инвалид I,II ст., участник боевых действий, сирота, чернобылец...).
        /// </summary>
        internal static string PrivilegesFull {
            get {
                return ResourceManager.GetString("PrivilegesFull", resourceCulture);
            }
        }
    }
}
