//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PersonalOffice_Step2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonalOffice_Step2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PersonalOffice_Step2", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочие паспорта.
        /// </summary>
        internal static string AnotherPassport {
            get {
                return ResourceManager.GetString("AnotherPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паспорт.
        /// </summary>
        internal static string HeaderPassport {
            get {
                return ResourceManager.GetString("HeaderPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В каком посольстве вы будете получать визу?.
        /// </summary>
        internal static string HeaderVisa {
            get {
                return ResourceManager.GetString("HeaderVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком длинное значение.
        /// </summary>
        internal static string LongValue_Message {
            get {
                return ResourceManager.GetString("LongValue_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия (если отличалась).
        /// </summary>
        internal static string PassportAnotherSurname {
            get {
                return ResourceManager.GetString("PassportAnotherSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кем выдан.
        /// </summary>
        internal static string PassportAuthor {
            get {
                return ResourceManager.GetString("PassportAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код подразделения.
        /// </summary>
        internal static string PassportCode {
            get {
                return ResourceManager.GetString("PassportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выдачи.
        /// </summary>
        internal static string PassportDate {
            get {
                return ResourceManager.GetString("PassportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of expire.
        /// </summary>
        internal static string PassportExpire {
            get {
                return ResourceManager.GetString("PassportExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PassportExpireMessage {
            get {
                return ResourceManager.GetString("PassportExpireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите, кем выдан паспорт.
        /// </summary>
        internal static string PassportInfo_PassportAuthor_Message {
            get {
                return ResourceManager.GetString("PassportInfo_PassportAuthor_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дату выдачи паспорта.
        /// </summary>
        internal static string PassportInfo_PassportDate_Message {
            get {
                return ResourceManager.GetString("PassportInfo_PassportDate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер паспорта.
        /// </summary>
        internal static string PassportInfo_PassportNumber_Message {
            get {
                return ResourceManager.GetString("PassportInfo_PassportNumber_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите серию паспорта.
        /// </summary>
        internal static string PassportInfo_PassportSeries_Message {
            get {
                return ResourceManager.GetString("PassportInfo_PassportSeries_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        internal static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серия.
        /// </summary>
        internal static string PassportSeries {
            get {
                return ResourceManager.GetString("PassportSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        internal static string PassportSurname {
            get {
                return ResourceManager.GetString("PassportSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        internal static string PassportType {
            get {
                return ResourceManager.GetString("PassportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер паспорта РФ должен состоять из 6 цифр без пробелов.
        /// </summary>
        internal static string RF_Number_Message {
            get {
                return ResourceManager.GetString("RF_Number_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серия паспорта РФ должна состоять из 4 цифр без пробелов.
        /// </summary>
        internal static string RF_Series_Message {
            get {
                return ResourceManager.GetString("RF_Series_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СНИЛС.
        /// </summary>
        internal static string SNILS {
            get {
                return ResourceManager.GetString("SNILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страховой номер индивидуального лицевого счёта.
        /// </summary>
        internal static string SNILS_title {
            get {
                return ResourceManager.GetString("SNILS_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        internal static string VisaCountryName {
            get {
                return ResourceManager.GetString("VisaCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите страну.
        /// </summary>
        internal static string VisaCountryNameMessage {
            get {
                return ResourceManager.GetString("VisaCountryNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        internal static string VisaPostAddress {
            get {
                return ResourceManager.GetString("VisaPostAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите адрес.
        /// </summary>
        internal static string VisaPostAddressMessage {
            get {
                return ResourceManager.GetString("VisaPostAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        internal static string VisaTownName {
            get {
                return ResourceManager.GetString("VisaTownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите город.
        /// </summary>
        internal static string VisaTownNameMessage {
            get {
                return ResourceManager.GetString("VisaTownNameMessage", resourceCulture);
            }
        }
    }
}
