//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PriorityChangerForeign {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PriorityChangerForeign() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PriorityChangerForeign", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявления отсортированы в порядке по убыванию. Наивысший приоритет имеет самое верхнее заявление. Чтобы изменить приоритет заявления, просто перетащите его на нужную позицию. Обращаем Ваше внимание!
        ///Прежде чем переходить к выбору  приоритетов  профилей в рамках каждой их программ, Вам необходимо подтвердить и сохранить   выбранную приоритетность программ!.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление.
        /// </summary>
        internal static string LicenseProgram {
            get {
                return ResourceManager.GetString("LicenseProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение приоритетов.
        /// </summary>
        internal static string MainHeader {
            get {
                return ResourceManager.GetString("MainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение приоритетов заявлений.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экзамен по выбору.
        /// </summary>
        internal static string ManualExam {
            get {
                return ResourceManager.GetString("ManualExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образовательная программа.
        /// </summary>
        internal static string ObrazProgram {
            get {
                return ResourceManager.GetString("ObrazProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приоритеты образовательных программ и профилей.
        /// </summary>
        internal static string ObrazPr_Message1 {
            get {
                return ResourceManager.GetString("ObrazPr_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расставьте приоритеты образовательных программ внутри конкурса и нажмите Сохранить..
        /// </summary>
        internal static string ObrazPr_Message2 {
            get {
                return ResourceManager.GetString("ObrazPr_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приоритет.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основа обучения.
        /// </summary>
        internal static string StudyBasis {
            get {
                return ResourceManager.GetString("StudyBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма обучения.
        /// </summary>
        internal static string StudyForm {
            get {
                return ResourceManager.GetString("StudyForm", resourceCulture);
            }
        }
    }
}
