//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Registration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registration() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Registration", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Зарегистрироваться.
        /// </summary>
        internal static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Для защиты от автоматической регистрации, введите слова ниже:.
        /// </summary>
        internal static string CaptchaHeader {
            get {
                return ResourceManager.GetString("CaptchaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Подтвердите пароль.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Адрес электронной почты.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Следующие категории граждан имеют права, равные с правами граждан Российской Федерации:&lt;br /&gt;
        ///                    &lt;ul&gt;
        ///                        &lt;li&gt;Граждане Республики Беларусь, Республики Казахстан, Кыргызской Республики, Республики Таджикистан&lt;/li&gt;
        ///                        &lt;li&gt;Граждане Республики Армения, Республики Молдова, Туркменистана, Республики Узбекистан, Украина, Грузии, постоянно проживающие на территории Российской Федерации и имеющие документы, подтверждающие правомерность их пребывания на тер [остаток строки был усечен]&quot;;.
        /// </summary>
        internal static string ForeignersInfo {
            get {
                return ResourceManager.GetString("ForeignersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Данные учётной записи.
        /// </summary>
        internal static string HeaderAccountInfo {
            get {
                return ResourceManager.GetString("HeaderAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как При создании учётной записи возникли следующие ошибки:.
        /// </summary>
        internal static string HeaderErrors {
            get {
                return ResourceManager.GetString("HeaderErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Длина пароля должна составлять минимум 6 символов..
        /// </summary>
        internal static string HeaderMinPasswordLength {
            get {
                return ResourceManager.GetString("HeaderMinPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Я иностранец.
        /// </summary>
        internal static string IsForeigner {
            get {
                return ResourceManager.GetString("IsForeigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Информация для иностранных граждан имеющих равные права с гражданами РФ.
        /// </summary>
        internal static string IsForeignerSpan {
            get {
                return ResourceManager.GetString("IsForeignerSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Я гражданин РФ или имею равные с ним права.
        /// </summary>
        internal static string IsRussian {
            get {
                return ResourceManager.GetString("IsRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Укажите, являетесь ли Вы гражданином РФ или иностранцем.
        /// </summary>
        internal static string NoForeignNoRussian {
            get {
                return ResourceManager.GetString("NoForeignNoRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Выберите что-то одно.
        /// </summary>
        internal static string NoTwoCheckboxes {
            get {
                return ResourceManager.GetString("NoTwoCheckboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Регистрация нового пользователя.
        /// </summary>
        internal static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
    }
}
