//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Registration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Registration", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        internal static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для защиты от автоматической регистрации, введите слова ниже:.
        /// </summary>
        internal static string CaptchaHeader {
            get {
                return ResourceManager.GetString("CaptchaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующие категории граждан имеют права, равные с правами граждан Российской Федерации:&lt;br /&gt;
        ///                    &lt;ul&gt;
        ///                        &lt;li&gt;Граждане Республики Беларусь, Республики Казахстан, Кыргызской Республики, Республики Таджикистан&lt;/li&gt;
        ///                        &lt;li&gt;Граждане Республики Армения, Республики Молдова, Туркменистана, Республики Узбекистан, Украина, Грузии, постоянно проживающие на территории Российской Федерации и имеющие документы, подтверждающие правомерность их пребывания на тер [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForeignersInfo {
            get {
                return ResourceManager.GetString("ForeignersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные учётной записи.
        /// </summary>
        internal static string HeaderAccountInfo {
            get {
                return ResourceManager.GetString("HeaderAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При создании учётной записи возникли следующие ошибки:.
        /// </summary>
        internal static string HeaderErrors {
            get {
                return ResourceManager.GetString("HeaderErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина пароля должна составлять минимум 6 символов..
        /// </summary>
        internal static string HeaderMinPasswordLength {
            get {
                return ResourceManager.GetString("HeaderMinPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я иностранец.
        /// </summary>
        internal static string IsForeigner {
            get {
                return ResourceManager.GetString("IsForeigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация для иностранных граждан имеющих равные права с гражданами РФ.
        /// </summary>
        internal static string IsForeignerSpan {
            get {
                return ResourceManager.GetString("IsForeignerSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я гражданин РФ или имею равные с ним права.
        /// </summary>
        internal static string IsRussian {
            get {
                return ResourceManager.GetString("IsRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите, являетесь ли Вы гражданином РФ или иностранцем.
        /// </summary>
        internal static string NoForeignNoRussian {
            get {
                return ResourceManager.GetString("NoForeignNoRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите что-то одно.
        /// </summary>
        internal static string NoTwoCheckboxes {
            get {
                return ResourceManager.GetString("NoTwoCheckboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация нового пользователя.
        /// </summary>
        internal static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
    }
}
