//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTimetable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamTimetable()
        {
            this.ApplicationSelectedExam = new HashSet<ApplicationSelectedExam>();
        }
    
        public int Id { get; set; }
        public System.Guid ExamInEntryBlockUnitId { get; set; }
        public System.DateTime ExamDate { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfClose { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationSelectedExam> ApplicationSelectedExam { get; set; }
        public virtual ExamInEntryBlockUnit ExamInEntryBlockUnit { get; set; }
    }
}
