//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonChangeStudyFormReason
    {
        public System.Guid PersonId { get; set; }
        public string Reason { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public Nullable<System.Guid> CommitId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ApplicationCommit ApplicationCommit { get; set; }
        public virtual Person Person { get; set; }
    }
}
