//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonFile
    {
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public string FileName { get; set; }
        public int FileSize { get; set; }
        public string FileExtention { get; set; }
        public byte[] FileData { get; set; }
        public string Comment { get; set; }
        public System.DateTime LoadDate { get; set; }
        public string MimeType { get; set; }
        public bool IsReadOnly { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string FailReason { get; set; }
        public int PersonFileTypeId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
