//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAbit2013
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioFilesMark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PortfolioFilesMark()
        {
            this.StatusId = 7;
        }
    
        public System.Guid PersonId { get; set; }
        public bool IsComplete { get; set; }
        public Nullable<double> RuPortfolioPts { get; set; }
        public Nullable<double> DePortfolioPts { get; set; }
        public Nullable<double> RuInterviewPts { get; set; }
        public Nullable<double> DeInterviewPts { get; set; }
        public Nullable<bool> Interview { get; set; }
        public int StatusId { get; set; }
    
        public virtual PortfolioStatus PortfolioStatus { get; set; }
    }
}
